feat(vscode): Port to VSCode
BingyanStudio/LapisCV pull request #17
Opened 2024-09-11 13:02 UTC by GoForceX

Add VSCode version and corresponding guide to enhance usability for newcomers.

2024-09-11 13:49 UTC, ligen131 commented
Preview: 
![image](https://github.com/user-attachments/assets/6e4f970f-4e72-4a2f-8565-95557e7c3333)

May have issues with dark themes
![image](https://github.com/user-attachments/assets/023b0932-7521-4dc8-9b0b-92e58a2a3c5e)

Thanks for your contribution!

2024-09-11 13:56 UTC, YiNNx commented
There's no need to support a dark version for the cv style :thinking:  
Maybe just set the cv page background white ?

2024-09-11 13:58 UTC, ligen131 commented
> There's no need to support a dark version for the cv style 🤔

Yes, you're right. But in the VS Code preview, it is displayed according to the IDE theme.

2024-09-11 13:59 UTC, GoForceX commented
> May have issues with dark themes

Fixed in https://github.com/BingyanStudio/LapisCV/pull/17/commits/7d388bc323de46cf97b50bf4e8dd582a6c1e6524. PDF generation style is not touched.

Not preferring setting the preview background white, 

because it may cause eye damage to dark mode users working at midnight🤣

This commit just sets color & bg color properties as `unset`, so light mode users will not be impacted.

![image](https://github.com/user-attachments/assets/940990e5-4a63-43d4-ba67-f4611de4a69f)

2024-09-11 15:13 UTC, GoForceX commented
Actually, there is a huge inconsistency between this version and the original one. 

But I prefer the version on this pr more.

Should I update my version to make it looks like the same?

On this branch: 
![image](https://github.com/user-attachments/assets/c3a41352-41e9-47e4-998e-a8c78c8b5b4d)

Preview from repo: 
![image](https://github.com/user-attachments/assets/91b9db06-4dad-49e3-8878-b57ee949cbd4)

2024-09-11 15:34 UTC, YiNNx commented
> Should I update my version to make it looks like the same?

Feel free to keep the changes!

2024-09-13 16:09 UTC, YiNNx requested changes

2024-09-14 04:02 UTC, GoForceX commented on README.md
> +2. 搜索 Markdown-pdf › Margin，并修改四边边距。<br>
Choose method 2 to be the main one, and preserved method 1 as an alternative method.

2024-09-14 04:04 UTC, GoForceX commented on README.md
> +3. 打开模版文件 [template.md](vscode/template.md) 进行内容编辑，右键选择 Markdown PDF - Export (pdf) 即可导出 PDF 文件。
Leave vscode/template.md as it is to ensure relative path relationship.

2024-09-14 04:04 UTC, GoForceX commented on vscode/lapis-cv.css
> +    padding-top: 12mm;
Added padding-bottom: 12mm;

2024-09-14 04:06 UTC, GoForceX commented on vscode/lapis-cv.css
> +  box-shadow: 0 0 0 3mm var(--bg-color);
@media screen {
  img[alt="avatar"] {
    box-shadow: 0 0 0 3mm var(--vscode-editor-background);
  }
}

2024-09-14 04:07 UTC, GoForceX commented on vscode/lapis-cv.css
> +  body {
Done.

2024-09-14 04:11 UTC, GoForceX commented on vscode/lapis-cv.css
> +    right: 0;
```css
@media screen {
  img[alt="avatar"] {
    position: relative;
    top: 0;
    right: 0;
  }
}
```

2024-09-14 04:12 UTC, GoForceX commented
Preview: 

![image](https://github.com/user-attachments/assets/a0b1e8eb-027a-406a-97e9-0d849bb5a89a)
![image](https://github.com/user-attachments/assets/1bd6b211-4953-4bcc-9489-d0125f56c6ac)

2024-09-14 04:26 UTC, YiNNx approved these changes

2024-09-14 04:27 UTC, merged